export const addOnData = [
  {
    id: "1",
    name: "O2 Voice & Data - 5GB",
    description: "5GB plan for light users.",
    price: 6.0,
    tooltip: "Ideal for browsing and messaging.",
    network: "O2",
    data: "5GB",
  },
  {
    id: "2",
    name: "O2 Voice & Data - 10GB",
    description: "10GB plan for average use.",
    price: 8.0,
    tooltip: "Best for streaming and daily use.",
    network: "O2",
    data: "10GB",
  },
  {
    id: "3",
    name: "O2 Voice & Data - Unlimited",
    description: "Unlimited data for power users.",
    price: 12.0,
    tooltip: "Perfect for unlimited streaming and hotspot use.",
    network: "O2",
    data: "Unlimited",
  },
  {
    id: "4",
    name: "Vodafone Voice & Data - 5GB",
    description: "Vodafone 5GB for light browsing.",
    price: 6.5,
    tooltip: "Reliable access to social and maps.",
    network: "Vodafone",
    data: "5GB",
  },
  {
    id: "5",
    name: "Vodafone Voice & Data - 50GB",
    description: "High data bundle for busy users.",
    price: 10.0,
    tooltip: "Supports calls, video, and more.",
    network: "Vodafone",
    data: "50GB",
  },
  {
    id: "6",
    name: "Vodafone Voice & Data - Unlimited",
    description: "Unlimited plan with extra speed.",
    price: 13.0,
    tooltip: "Best for tethering and remote work.",
    network: "Vodafone",
    data: "Unlimited",
  },
  {
    id: "7",
    name: "EE Voice & Data - 10GB",
    description: "Balanced usage plan.",
    price: 7.5,
    tooltip: "Stream music, scroll socials.",
    network: "EE",
    data: "10GB",
  },
  {
    id: "8",
    name: "EE Voice & Data - 100GB",
    description: "Huge data volume for pro users.",
    price: 14.0,
    tooltip: "Gaming, video calls, and beyond.",
    network: "EE",
    data: "100GB",
  },
  {
    id: "9",
    name: "Three Voice & Data - 20GB",
    description: "Three plan for everyday power use.",
    price: 9.0,
    tooltip: "Ideal for commuters and travellers.",
    network: "Three",
    data: "20GB",
  },
  {
    id: "10",
    name: "Three Voice & Data - Unlimited",
    description: "Unlimited everything on Three.",
    price: 11.0,
    tooltip: "The ultimate no-limits package.",
    network: "Three",
    data: "Unlimited",
  },
];
