export type MobilePlan = {
  id: number;
  network: string;
  name: string;
  minutes: string;
  sms: string;
  data: string;
  ukEuMins: string;
  icons: string[];
  price: string;
  setup: string;
  term: string;
  type: string;
};

export const mobilePlanData: MobilePlan[] = [
  {
    id: 1,
    network: "O2",
    name: "O2 Unlimited Plan",
    minutes: "Unlimited",
    sms: "Unlimited",
    data: "Unlimited",
    ukEuMins: "1000",
    icons: ["phone", "plane"],
    price: "£19/month",
    setup: "£0/set up",
    term: "12 months",
    type: "Voice & Data",
  },
  {
    id: 2,
    network: "Vodafone",
    name: "Vodafone Basic 5GB",
    minutes: "500",
    sms: "Unlimited",
    data: "5GB",
    ukEuMins: "100",
    icons: ["globe"],
    price: "£15/month",
    setup: "£0/set up",
    term: "12 months",
    type: "Voice only",
  },
  {
    id: 3,
    network: "EE",
    name: "EE Max 100GB",
    minutes: "Unlimited",
    sms: "Unlimited",
    data: "100GB",
    ukEuMins: "Unlimited",
    icons: ["wifi", "globe"],
    price: "£25/month",
    setup: "£10/set up",
    term: "24 months",
    type: "Voice & Data",
  },
  {
    id: 4,
    network: "Three",
    name: "Three Essentials 20GB",
    minutes: "Unlimited",
    sms: "Unlimited",
    data: "20GB",
    ukEuMins: "0",
    icons: ["phone"],
    price: "£12/month",
    setup: "£0/set up",
    term: "30 days",
    type: "Mobile broadband",
  },
  {
    id: 5,
    network: "O2",
    name: "O2 Roam Plus",
    minutes: "Unlimited",
    sms: "Unlimited",
    data: "50GB",
    ukEuMins: "2000",
    icons: ["plane", "globe"],
    price: "£29/month",
    setup: "£15/set up",
    term: "24 months",
    type: "Voice & Data",
  },
  {
    id: 6,
    network: "Vodafone",
    name: "Vodafone Lite 10GB",
    minutes: "1000",
    sms: "1000",
    data: "10GB",
    ukEuMins: "500",
    icons: ["wifi"],
    price: "£18/month",
    setup: "£5/set up",
    term: "12 months",
    type: "Voice only",
  },
  {
    id: 7,
    network: "EE",
    name: "EE Starter 20GB",
    minutes: "Unlimited",
    sms: "Unlimited",
    data: "20GB",
    ukEuMins: "1000",
    icons: ["phone"],
    price: "£17/month",
    setup: "£0/set up",
    term: "12 months",
    type: "Voice only",
  },
  {
    id: 8,
    network: "Three",
    name: "Three Roaming 30GB",
    minutes: "1000",
    sms: "Unlimited",
    data: "30GB",
    ukEuMins: "Unlimited",
    icons: ["plane", "globe"],
    price: "£21/month",
    setup: "£10/set up",
    term: "24 months",
    type: "Voice & Data",
  },
  {
    id: 9,
    network: "Gamma",
    name: "Gamma Mobile 10GB",
    minutes: "Unlimited",
    sms: "Unlimited",
    data: "10GB",
    ukEuMins: "500",
    icons: ["wifi"],
    price: "£14/month",
    setup: "£5/set up",
    term: "12 months",
    type: "Voice only",
  },
  {
    id: 10,
    network: "Vodafone",
    name: "Vodafone Red 100GB",
    minutes: "Unlimited",
    sms: "Unlimited",
    data: "100GB",
    ukEuMins: "2000",
    icons: ["phone", "globe"],
    price: "£27/month",
    setup: "£0/set up",
    term: "24 months",
    type: "Voice & Data",
  },
  {
    id: 11,
    network: "EE",
    name: "EE Family 25GB",
    minutes: "Unlimited",
    sms: "Unlimited",
    data: "25GB",
    ukEuMins: "1000",
    icons: ["wifi", "plane"],
    price: "£22/month",
    setup: "£0/set up",
    term: "12 months",
    type: "Mobile broadband",
  },
  {
    id: 12,
    network: "Three",
    name: "Three Max 40GB",
    minutes: "Unlimited",
    sms: "Unlimited",
    data: "40GB",
    ukEuMins: "Unlimited",
    icons: ["globe"],
    price: "£23/month",
    setup: "£10/set up",
    term: "24 months",
    type: "Voice & Data",
  },
  {
    id: 13,
    network: "O2",
    name: "O2 Data Boost 15GB",
    minutes: "Unlimited",
    sms: "Unlimited",
    data: "15GB",
    ukEuMins: "500",
    icons: ["wifi"],
    price: "£16/month",
    setup: "£0/set up",
    term: "12 months",
    type: "Mobile broadband",
  },
  {
    id: 14,
    network: "Vodafone",
    name: "Vodafone Flex 5GB",
    minutes: "500",
    sms: "500",
    data: "5GB",
    ukEuMins: "250",
    icons: ["phone"],
    price: "£11/month",
    setup: "£0/set up",
    term: "30 days",
    type: "Voice only",
  },
  {
    id: 15,
    network: "Gamma",
    name: "Gamma Unlimited",
    minutes: "Unlimited",
    sms: "Unlimited",
    data: "Unlimited",
    ukEuMins: "Unlimited",
    icons: ["phone", "plane", "globe"],
    price: "£30/month",
    setup: "£0/set up",
    term: "24 months",
    type: "Voice & Data",
  },
];
